# SPDX-License-Identifier: Apache-2.0
"""Smoke tests for `i2w gallery build`.

The gallery command renders every V1 template against its canonical demo
vars and writes one ``<domain>.md`` file. These tests verify that the
output is shaped correctly without touching the real ``docs/gallery/``
tree.
"""
from __future__ import annotations

from pathlib import Path

from typer.testing import CliRunner

from image2_workbench.cli import app

runner = CliRunner()
REPO_ROOT = Path(__file__).resolve().parents[2]


def test_gallery_build_writes_four_domain_files(tmp_path: Path) -> None:
    out_dir = tmp_path / "gallery"
    result = runner.invoke(app, ["gallery", "build", "--out-dir", str(out_dir)])
    assert result.exit_code == 0, (result.stdout, result.stderr)
    expected = {"business.md", "academic.md", "uiux.md", "anime.md"}
    actual = {p.name for p in out_dir.glob("*.md")}
    assert expected <= actual, f"missing domain files; got {actual}"
    for name in expected:
        path = out_dir / name
        size = path.stat().st_size
        assert size >= 1024, f"{name} too small ({size} bytes)"
        body = path.read_text(encoding="utf-8")
        assert "Path A" in body, f"{name} missing 'Path A' guidance"
        # Each domain has 4 templates -> at least 4 H2 sections.
        sections = [line for line in body.splitlines() if line.startswith("## ")]
        assert len(sections) >= 4, (
            f"{name} only has {len(sections)} template sections"
        )


def test_gallery_build_skips_index_md(tmp_path: Path) -> None:
    out_dir = tmp_path / "gallery"
    # Pre-seed an index.md to verify the build doesn't overwrite it.
    out_dir.mkdir(parents=True)
    sentinel = "# my hand-curated index\n"
    (out_dir / "index.md").write_text(sentinel, encoding="utf-8")

    result = runner.invoke(app, ["gallery", "build", "--out-dir", str(out_dir)])
    assert result.exit_code == 0, (result.stdout, result.stderr)
    assert (out_dir / "index.md").read_text(encoding="utf-8") == sentinel


def test_gallery_build_filters_by_domain(tmp_path: Path) -> None:
    out_dir = tmp_path / "gallery"
    result = runner.invoke(
        app, ["gallery", "build", "--out-dir", str(out_dir), "--domain", "business"]
    )
    assert result.exit_code == 0, (result.stdout, result.stderr)
    business = out_dir / "business.md"
    assert business.exists()
    # Other domain files must NOT appear when --domain is set.
    assert not (out_dir / "academic.md").exists()
    assert not (out_dir / "anime.md").exists()
    assert not (out_dir / "uiux.md").exists()


def test_gallery_build_bilingual_blocks_are_present(tmp_path: Path) -> None:
    out_dir = tmp_path / "gallery"
    result = runner.invoke(app, ["gallery", "build", "--out-dir", str(out_dir)])
    assert result.exit_code == 0, (result.stdout, result.stderr)
    body = (out_dir / "business.md").read_text(encoding="utf-8")
    assert "### English" in body
    assert "### 中文" in body
    # The renderer un-doubles inner quotes; the SWOT card should now
    # render `- header: "..."` (one set), not `""..."" `.
    assert '""' not in body


def test_checked_in_gallery_matches_generated_output(tmp_path: Path) -> None:
    out_dir = tmp_path / "gallery"
    result = runner.invoke(app, ["gallery", "build", "--out-dir", str(out_dir)])
    assert result.exit_code == 0, (result.stdout, result.stderr)
    for domain in ("business", "academic", "uiux", "anime"):
        checked_in = (REPO_ROOT / "docs" / "gallery" / f"{domain}.md").read_text(
            encoding="utf-8"
        )
        generated = (out_dir / f"{domain}.md").read_text(encoding="utf-8")
        assert checked_in == generated, f"docs/gallery/{domain}.md is stale"


# --------------------------------------------------------------------------- #
# `i2w gallery readme` smoke tests — output / inject / check / mode validation.
# --------------------------------------------------------------------------- #

_BEGIN_MARKER = (
    "<!-- BEGIN GALLERY (auto-generated by `i2w gallery readme`; do not edit by hand) -->"
)
_END_MARKER = "<!-- END GALLERY -->"


def test_gallery_readme_out_en_writes_section(tmp_path: Path) -> None:
    target = tmp_path / "readme-en.md"
    result = runner.invoke(
        app,
        ["gallery", "readme", "--lang", "en", "--out", str(target)],
    )
    assert result.exit_code == 0, (result.stdout, result.stderr)
    body = target.read_text(encoding="utf-8")
    assert "16 domains" in body
    assert "52 templates" in body
    # At least one V1 template id from each V1 domain must appear.
    assert "business_swot_card" in body
    assert "academic_scientific_diagram" in body
    assert "uiux_ios_app_mockup" in body
    assert "anime_character_sheet" in body
    assert _BEGIN_MARKER in body
    assert _END_MARKER in body


def test_gallery_readme_out_zh_contains_chinese_chars(tmp_path: Path) -> None:
    target = tmp_path / "readme-zh.md"
    result = runner.invoke(
        app,
        ["gallery", "readme", "--lang", "zh-CN", "--out", str(target)],
    )
    assert result.exit_code == 0, (result.stdout, result.stderr)
    body = target.read_text(encoding="utf-8")
    # Localised heading and sub-table headers must be present.
    assert "模板图册" in body
    assert "| 模板 | 尺寸 | 评测 |" in body
    assert "16 个领域" in body


def test_gallery_readme_inject_replaces_section_between_markers(tmp_path: Path) -> None:
    target = tmp_path / "README.md"
    target.write_text(
        "# Project README\n\n"
        "## Intro paragraph\n\n"
        f"{_BEGIN_MARKER}\nold body\n{_END_MARKER}\n\n"
        "## Footer\n",
        encoding="utf-8",
    )
    result = runner.invoke(
        app,
        ["gallery", "readme", "--lang", "en", "--inject", str(target)],
    )
    assert result.exit_code == 0, (result.stdout, result.stderr)
    body = target.read_text(encoding="utf-8")
    assert "old body" not in body
    assert "## Intro paragraph" in body
    assert "## Footer" in body
    assert "## Atlas — 16 domains, 52 templates" in body
    # Re-injecting should be idempotent (round-trip safe).
    snapshot = body
    second = runner.invoke(
        app,
        ["gallery", "readme", "--lang", "en", "--inject", str(target)],
    )
    assert second.exit_code == 0, (second.stdout, second.stderr)
    assert target.read_text(encoding="utf-8") == snapshot


def test_gallery_readme_check_drift_exits_4(tmp_path: Path) -> None:
    target = tmp_path / "README.md"
    # File has markers but stale content between them.
    target.write_text(
        "# Project\n\n"
        f"{_BEGIN_MARKER}\nstale gallery\n{_END_MARKER}\n",
        encoding="utf-8",
    )
    result = runner.invoke(
        app,
        ["gallery", "readme", "--lang", "en", "--check", str(target)],
    )
    assert result.exit_code == 4, (result.stdout, result.stderr)


def test_gallery_readme_check_passes_after_inject(tmp_path: Path) -> None:
    target = tmp_path / "README.md"
    target.write_text(
        f"# Project\n\n{_BEGIN_MARKER}\nstale\n{_END_MARKER}\n",
        encoding="utf-8",
    )
    inject_result = runner.invoke(
        app,
        ["gallery", "readme", "--lang", "en", "--inject", str(target)],
    )
    assert inject_result.exit_code == 0, (inject_result.stdout, inject_result.stderr)
    check_result = runner.invoke(
        app,
        ["gallery", "readme", "--lang", "en", "--check", str(target)],
    )
    assert check_result.exit_code == 0, (check_result.stdout, check_result.stderr)


def test_gallery_readme_no_mode_exits_4(tmp_path: Path) -> None:
    result = runner.invoke(app, ["gallery", "readme", "--lang", "en"])
    assert result.exit_code == 4, (result.stdout, result.stderr)


def test_gallery_readme_two_modes_exits_4(tmp_path: Path) -> None:
    target = tmp_path / "README.md"
    target.write_text(
        f"# x\n{_BEGIN_MARKER}\nold\n{_END_MARKER}\n", encoding="utf-8"
    )
    out = tmp_path / "out.md"
    result = runner.invoke(
        app,
        [
            "gallery",
            "readme",
            "--lang",
            "en",
            "--out",
            str(out),
            "--inject",
            str(target),
        ],
    )
    assert result.exit_code == 4, (result.stdout, result.stderr)


def test_gallery_readme_inject_missing_marker_exits_4(tmp_path: Path) -> None:
    target = tmp_path / "README.md"
    target.write_text("# README without markers\n", encoding="utf-8")
    result = runner.invoke(
        app,
        ["gallery", "readme", "--lang", "en", "--inject", str(target)],
    )
    assert result.exit_code == 4, (result.stdout, result.stderr)
