# SPDX-License-Identifier: Apache-2.0
"""`i2w gallery build` / `i2w gallery readme` — paste-ready gallery surfaces.

The gallery is the L3 (no-runtime) surface of the workbench: pre-rendered
markdown that anyone can copy into web ChatGPT. ``build`` walks the
template index, renders every template with its canonical demo vars, and
writes one ``<domain>.md`` file per V1 domain. ``readme`` is the L0
no-friction surface: it produces a compact inline-atlas section for the
GitHub homepage README, optionally injecting it between marker comments
in a target file (round-trip-safe — re-injecting after edits doesn't
drift). The shared ``index.md`` under ``docs/gallery/`` is owned
elsewhere and is *not* touched here.
"""
from __future__ import annotations

import os
import re
from pathlib import Path
from typing import Annotated

import typer
from rich.console import Console

from ..catalog import index as catalog_index
from ..compiler.loader import load_template, load_vars, resolve_demo_vars
from ..compiler.renderer import render_both
from ..errors import cli_dispatch, validation_error

gallery_app = typer.Typer(
    no_args_is_help=True,
    help="Build markdown gallery from templates.",
)


# Legacy V1 template -> demo-vars overrides. New templates should follow
# the ``<template_stem>.yml`` convention inside ``_vars_examples/``; entries
# here cover the V1 templates whose demo filenames predate that convention.
# Mirrors ``DEMO_VARS_MAP_LEGACY`` in
# ``tests/unit/test_all_templates_load.py`` so the command never depends on
# tests at runtime.
_DEMO_VARS_MAP_LEGACY: dict[str, str] = {
    "business/swot_card": "business/_vars_examples/swot_acme.yml",
    "business/pitch_slide": "business/_vars_examples/pitch_demo.yml",
    "business/linkedin_carousel": "business/_vars_examples/linkedin_demo.yml",
    "business/data_dashboard": "business/_vars_examples/dashboard_demo.yml",
    "academic/scientific_diagram": "academic/_vars_examples/diagram_demo.yml",
    "academic/chalkboard_proof": "academic/_vars_examples/proof_demo.yml",
    "academic/multilingual_eduposter": "academic/_vars_examples/eduposter_demo.yml",
    "academic/journal_poster": "academic/_vars_examples/journal_demo.yml",
    "uiux/ios_app_mockup": "uiux/_vars_examples/ios_app_demo.yml",
    "uiux/web_dashboard": "uiux/_vars_examples/web_dashboard_demo.yml",
    "uiux/design_system_card": "uiux/_vars_examples/design_system_demo.yml",
    "uiux/social_cover_xhs": "uiux/_vars_examples/xhs_cover_demo.yml",
    "anime/character_sheet": "anime/_vars_examples/character_demo.yml",
    "anime/comic_8panel": "anime/_vars_examples/comic_demo.yml",
    "anime/city_poster": "anime/_vars_examples/city_poster_demo.yml",
    "anime/ccd_candid": "anime/_vars_examples/ccd_demo.yml",
}


_HEADER_TEMPLATE = """<!-- SPDX-License-Identifier: CC-BY-4.0 -->
<!-- Generated by `i2w gallery build` from templates/{domain}/*.yml. \
Do not edit by hand. -->

# Gallery: {domain}

Auto-compiled from `templates/{domain}/*.yml`. Each section shows the bilingual
prompt for one template. Regenerate with `i2w gallery build`.

To use these prompts:
- **Path A (no Python):** copy a prompt block into web ChatGPT.
- **Path B (CLI):** `i2w template render <id> --vars <your-vars>.yml --out prompt.md`.

---
"""


def _vars_path_for(template_path: Path, templates_root: Path) -> Path | None:
    """Resolve the demo-vars file for ``template_path``.

    Convention-over-config: tries ``_DEMO_VARS_MAP_LEGACY`` first (so V1
    templates with non-conforming filenames keep working), then the
    ``<stem>.yml`` / ``<stem>_demo.yml`` / single-file conventions inside
    the sibling ``_vars_examples/`` directory. ``templates_root`` is
    accepted for symmetry with callers but the resolver uses
    ``template_path``'s grandparent internally.
    """
    del templates_root  # resolver derives templates_root from template_path
    return resolve_demo_vars(template_path, override=_DEMO_VARS_MAP_LEGACY)


def _render_template_section(
    template_path: Path,
    templates_root: Path,
) -> str:
    """Return the markdown section for one template (no leading separator)."""
    spec = load_template(template_path)
    vars_path = _vars_path_for(template_path, templates_root)
    if vars_path is None:
        raise FileNotFoundError(
            f"no demo-vars file resolved for {template_path}; "
            f"add a sibling _vars_examples/{template_path.stem}.yml or an entry "
            f"to gallery._DEMO_VARS_MAP_LEGACY"
        )
    vars_ = load_vars(vars_path)
    rendered = render_both(spec, vars_)

    art = spec.artifact
    descr = spec.description or art.type
    rel_vars = vars_path.relative_to(templates_root)
    parts: list[str] = []
    parts.append(f"## {spec.id}")
    parts.append("")
    parts.append(f"> {descr}")
    parts.append("")
    parts.append(
        f"**Artifact:** `{art.type}`, `{art.size}`, aspect `{art.aspect}`"
    )
    parts.append(f"**Demo vars:** `templates/{rel_vars}`")
    parts.append("")
    if "en" in rendered:
        parts.append("### English")
        parts.append("")
        parts.append("```")
        parts.append(rendered["en"])
        parts.append("```")
        parts.append("")
    if "zh-CN" in rendered:
        parts.append("### 中文")
        parts.append("")
        parts.append("```")
        parts.append(rendered["zh-CN"])
        parts.append("```")
        parts.append("")
    parts.append("---")
    parts.append("")
    return "\n".join(parts)


def _build_domain_file(
    domain: str,
    template_paths: list[Path],
    templates_root: Path,
) -> str:
    body = [_HEADER_TEMPLATE.format(domain=domain)]
    for tp in sorted(template_paths, key=lambda p: p.stem):
        body.append("")
        body.append(_render_template_section(tp, templates_root))
    return "\n".join(body).rstrip() + "\n"


@gallery_app.command("build")
def build(
    out_dir: Annotated[
        Path, typer.Option("--out-dir", help="Output directory for the gallery")
    ] = Path("docs/gallery"),
    domain: Annotated[
        str | None,
        typer.Option("--domain", help="Restrict to a single domain (e.g. business)"),
    ] = None,
) -> None:
    """Render every V1 template into its domain's gallery markdown file.

    Writes one file per domain under ``out_dir`` (e.g. ``business.md``).
    Skips ``index.md`` — that file is hand-curated. Returns the count of
    templates rendered and domain files written.
    """
    console = Console()
    out_dir.mkdir(parents=True, exist_ok=True)

    entries = catalog_index.list_templates(domain=domain)
    if not entries:
        console.print(
            f"no templates found (domain={domain!r})", markup=False
        )
        return

    templates_root = catalog_index._resolve_templates_dir()  # noqa: SLF001 — internal helper

    by_domain: dict[str, list[Path]] = {}
    for entry in entries:
        by_domain.setdefault(entry.domain, []).append(Path(entry.path))

    total_templates = 0
    domain_files = 0
    for dom, paths in sorted(by_domain.items()):
        content = _build_domain_file(dom, paths, templates_root)
        target = out_dir / f"{dom}.md"
        target.write_text(content, encoding="utf-8")
        domain_files += 1
        total_templates += len(paths)

    console.print(
        f"wrote {total_templates} templates across {domain_files} domain files",
        markup=False,
    )


# --------------------------------------------------------------------------- #
# `i2w gallery readme` — inline-atlas section for the homepage README.
# --------------------------------------------------------------------------- #

# Marker comments for round-trip-safe injection. The BEGIN marker tolerates
# the appended auto-generated suffix so re-runs find the section even after
# the body changed.
README_BEGIN_PREFIX = "<!-- BEGIN GALLERY"
README_END_MARKER = "<!-- END GALLERY -->"
README_BEGIN_FULL = (
    "<!-- BEGIN GALLERY (auto-generated by `i2w gallery readme`; "
    "do not edit by hand) -->"
)

_JINJA_PLACEHOLDER_RE = re.compile(r"\{\{[^}]+\}\}")
_WHITESPACE_RE = re.compile(r"\s+")

# Per-domain emoji glyph for compact atlas rows. ``social_media`` uses 🗯️ to
# avoid colliding with ``uiux`` (📱).
_DOMAIN_EMOJI: dict[str, str] = {
    "business": "📊",
    "academic": "🎓",
    "uiux": "📱",
    "anime": "🎌",
    "ecommerce": "🛍️",
    "industrial": "🏭",
    "product": "📦",
    "advertising": "📢",
    "social_media": "🗯️",
    "gaming": "🎮",
    "photography": "📷",
    "fashion": "👗",
    "food": "🍽️",
    "architecture": "🏛️",
    "interior": "🛋️",
    "travel": "✈️",
    "typography": "🔤",
    "beauty": "💄",
    "events": "🎫",
    "tattoo": "🪡",
    "watercolor_illustration": "🎨",
    "isometric_illustration": "🧊",
    "comic_book": "💥",
    "music": "🎵",
    "science_fiction_concept": "🚀",
    "infographic_data": "📈",
    "kids_illustration": "🧸",
    "automotive": "🚗",
    "pet": "🐾",
    "streetwear": "👟",
}


def _domain_emoji(domain: str) -> str:
    """Return the registered glyph for ``domain`` (or ``📁`` if unknown)."""
    return _DOMAIN_EMOJI.get(domain, "📁")


def _excerpt(spec_obj: object, max_chars: int = 60) -> str:
    """Return a one-line, Jinja-stripped, length-capped use-case teaser.

    Resolution: ``spec.description`` (if non-empty) > ``spec.spec.subject``.
    Strips Jinja ``{{var}}`` placeholders to ``…``, collapses whitespace,
    and truncates with a trailing ellipsis when over ``max_chars``.

    Accepts a ``TemplateSpec`` (preferred) but is duck-typed so tests can
    pass simple namespace objects.
    """
    description = getattr(spec_obj, "description", None) or ""
    subject = ""
    inner_spec = getattr(spec_obj, "spec", None)
    if inner_spec is not None:
        subject = getattr(inner_spec, "subject", "") or ""
    raw = (description or subject or "").strip()
    raw = _JINJA_PLACEHOLDER_RE.sub("…", raw)
    raw = _WHITESPACE_RE.sub(" ", raw).strip()
    if len(raw) > max_chars:
        raw = raw[: max_chars - 1].rstrip() + "…"
    return raw


def _generate_section(
    *,
    lang: str,
    max_excerpt_chars: int,
) -> str:
    """Build the compact inline-atlas section (markers included)."""
    entries = catalog_index.list_templates()
    by_domain: dict[str, list[Path]] = {}
    for entry in entries:
        by_domain.setdefault(entry.domain, []).append(Path(entry.path))

    domain_count = len(by_domain)
    template_count = sum(len(paths) for paths in by_domain.values())

    if lang == "zh-CN":
        header = f"## 模板图册 — {domain_count} 个领域，{template_count} 个模板"
        intro = (
            f"当前扩展图册覆盖 {domain_count} 个领域；每个领域都有一页可复制的双语 prompt "
            "gallery，也能从同一份 YAML 模板走 CLI / Skill / API。"
        )
        cols = ("领域", "模板数", "适合做什么", "代表模板", "入口")
        gallery_label = "图册"
        templates_label = "模板"
        docs_label = "继续看："
        docs_links = (
            '<a href="docs/getting-started.zh.md">快速上手</a> · '
            '<a href="docs/chatgpt-web-mode.md">网页 ChatGPT 用法</a> · '
            '<a href="docs/cost-modeling.md">成本模型</a>'
        )
    else:
        header = f"## Atlas — {domain_count} domains, {template_count} templates"
        intro = (
            f"The current extended atlas covers {domain_count} domains. Each domain has a "
            "copy-ready bilingual gallery page, and the same YAML templates drive "
            "CLI, Skill, and API workflows."
        )
        cols = ("Domain", "Templates", "Good for", "Representative templates", "Open")
        gallery_label = "Gallery"
        templates_label = "Templates"
        docs_label = "Read next:"
        docs_links = (
            '<a href="docs/getting-started.en.md">Getting started</a> · '
            '<a href="docs/chatgpt-web-mode.md">Web ChatGPT mode</a> · '
            '<a href="docs/cost-modeling.md">Cost modeling</a>'
        )

    parts: list[str] = [
        README_BEGIN_FULL,
        "",
        '<a id="atlas--30-domains-80-templates"></a>',
        header,
        "",
        intro,
        "",
    ]
    parts.append(f"| {cols[0]} | {cols[1]} | {cols[2]} | {cols[3]} | {cols[4]} |")
    parts.append("|---|---:|---|---|---|")

    sorted_domains = sorted(by_domain.items())
    for dom, paths in sorted_domains:
        sorted_paths = sorted(paths, key=lambda p: p.stem)
        specs = [load_template(path) for path in sorted_paths[:2]]
        excerpt_source = specs[0] if specs else load_template(sorted_paths[0])
        excerpt = _excerpt(excerpt_source, max_chars=max_excerpt_chars)
        excerpt = excerpt.replace("|", "\\|")
        reps = " · ".join(f"`{spec.id}`" for spec in specs)
        domain_label = f"{_domain_emoji(dom)} `{dom}`"
        links = (
            f'<a href="docs/gallery/{dom}.md">{gallery_label}</a> · '
            f'<a href="templates/{dom}/">{templates_label}</a>'
        )
        parts.append(
            f"| {domain_label} | {len(paths)} | {excerpt} | {reps} | {links} |"
        )
    parts.append("")
    parts.append(f"<p><strong>{docs_label}</strong> {docs_links}</p>")
    parts.append("")
    parts.append(README_END_MARKER)

    return "\n".join(parts)


def _replace_section(existing: str, section: str) -> str:
    """Replace the marker-delimited gallery section in ``existing`` with ``section``.

    Locates ``<!-- BEGIN GALLERY`` (just the prefix; tolerates the
    auto-generated suffix) and ``<!-- END GALLERY -->`` markers and
    swaps everything between them inclusive. Raises a workbench
    ``validation_error`` when either marker is missing.
    """
    begin_idx = existing.find(README_BEGIN_PREFIX)
    if begin_idx == -1:
        raise validation_error(
            "gallery_marker_missing",
            f"BEGIN GALLERY marker not found; expected line containing "
            f"{README_BEGIN_PREFIX!r}",
        )
    end_idx = existing.find(README_END_MARKER, begin_idx)
    if end_idx == -1:
        raise validation_error(
            "gallery_marker_missing",
            f"END GALLERY marker not found after BEGIN; expected "
            f"{README_END_MARKER!r}",
        )
    end_idx += len(README_END_MARKER)
    return existing[:begin_idx] + section + existing[end_idx:]


def _atomic_write(target: Path, content: str) -> None:
    """Write ``content`` to ``target`` atomically via a sibling tmp file."""
    tmp = target.with_suffix(target.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    os.replace(tmp, target)


@gallery_app.command("readme")
def readme(
    lang: Annotated[str, typer.Option("--lang", help="zh-CN | en")] = "en",
    out: Annotated[
        Path | None,
        typer.Option("--out", help="Write the section to this file"),
    ] = None,
    inject: Annotated[
        Path | None,
        typer.Option(
            "--inject",
            help=(
                "Replace content between <!-- BEGIN GALLERY --> and "
                "<!-- END GALLERY --> markers in this file"
            ),
        ),
    ] = None,
    check: Annotated[
        Path | None,
        typer.Option(
            "--check",
            help="Verify the file's gallery section is up to date; exit 4 if drift",
        ),
    ] = None,
    max_excerpt_chars: Annotated[
        int,
        typer.Option("--max-excerpt-chars", help="Max chars of prompt excerpt per card"),
    ] = 90,
) -> None:
    """Generate the inline-atlas section for README.{md,zh.md}."""
    console = Console()

    def _run() -> None:
        modes = [m for m in (out, inject, check) if m is not None]
        if len(modes) != 1:
            raise validation_error(
                "gallery_readme_mode",
                "exactly one of --out, --inject, --check is required",
                context={
                    "out": str(out) if out is not None else None,
                    "inject": str(inject) if inject is not None else None,
                    "check": str(check) if check is not None else None,
                },
            )

        if lang not in ("zh-CN", "en"):
            raise validation_error(
                "gallery_readme_lang",
                f"unsupported --lang {lang!r}; expected 'en' or 'zh-CN'",
                context={"lang": lang},
            )

        section = _generate_section(lang=lang, max_excerpt_chars=max_excerpt_chars)

        if out is not None:
            out.parent.mkdir(parents=True, exist_ok=True)
            _atomic_write(out, section + "\n")
            console.print(
                f"wrote gallery section ({len(section)} chars) to {out}",
                markup=False,
            )
            return

        if inject is not None:
            if not inject.is_file():
                raise validation_error(
                    "gallery_readme_target_missing",
                    f"target file not found: {inject}",
                    context={"target": str(inject)},
                )
            existing = inject.read_text(encoding="utf-8")
            updated = _replace_section(existing, section)
            _atomic_write(inject, updated)
            console.print(
                f"injected gallery section into {inject}",
                markup=False,
            )
            return

        if check is not None:
            if not check.is_file():
                raise validation_error(
                    "gallery_readme_target_missing",
                    f"target file not found: {check}",
                    context={"target": str(check)},
                )
            existing = check.read_text(encoding="utf-8")
            updated = _replace_section(existing, section)
            if existing != updated:
                raise validation_error(
                    "gallery_section_drift",
                    f"{check} gallery section is out of date; "
                    f"run `i2w gallery readme --inject {check}` to refresh",
                    context={"target": str(check)},
                )
            console.print(
                f"{check} gallery section is up to date",
                markup=False,
            )
            return

    raise SystemExit(cli_dispatch(_run))


__all__ = ["gallery_app"]
