# SPDX-License-Identifier: Apache-2.0
"""`i2w gallery build` — compile the bilingual paste-ready gallery from templates.

The gallery is the L3 (no-runtime) surface of the workbench: pre-rendered
markdown that anyone can copy into web ChatGPT. This command walks the
template index, renders every template with its canonical demo vars, and
writes one ``<domain>.md`` file per V1 domain. The shared ``index.md``
under ``docs/gallery/`` is owned elsewhere and is *not* touched here.
"""
from __future__ import annotations

from pathlib import Path
from typing import Annotated

import typer
from rich.console import Console

from ..catalog import index as catalog_index
from ..compiler.loader import load_template, load_vars
from ..compiler.renderer import render_both

gallery_app = typer.Typer(
    no_args_is_help=True,
    help="Build markdown gallery from templates.",
)


# Canonical template -> demo-vars map. Mirrors the source-of-truth in
# ``tests/unit/test_all_templates_load.py``; kept inline here so the
# command never depends on tests at runtime. New templates must be added
# in both places.
_DEMO_VARS_MAP: dict[str, str] = {
    "business/swot_card": "business/_vars_examples/swot_acme.yml",
    "business/pitch_slide": "business/_vars_examples/pitch_demo.yml",
    "business/linkedin_carousel": "business/_vars_examples/linkedin_demo.yml",
    "business/data_dashboard": "business/_vars_examples/dashboard_demo.yml",
    "academic/scientific_diagram": "academic/_vars_examples/diagram_demo.yml",
    "academic/chalkboard_proof": "academic/_vars_examples/proof_demo.yml",
    "academic/multilingual_eduposter": "academic/_vars_examples/eduposter_demo.yml",
    "academic/journal_poster": "academic/_vars_examples/journal_demo.yml",
    "uiux/ios_app_mockup": "uiux/_vars_examples/ios_app_demo.yml",
    "uiux/web_dashboard": "uiux/_vars_examples/web_dashboard_demo.yml",
    "uiux/design_system_card": "uiux/_vars_examples/design_system_demo.yml",
    "uiux/social_cover_xhs": "uiux/_vars_examples/xhs_cover_demo.yml",
    "anime/character_sheet": "anime/_vars_examples/character_demo.yml",
    "anime/comic_8panel": "anime/_vars_examples/comic_demo.yml",
    "anime/city_poster": "anime/_vars_examples/city_poster_demo.yml",
    "anime/ccd_candid": "anime/_vars_examples/ccd_demo.yml",
}


_HEADER_TEMPLATE = """<!-- SPDX-License-Identifier: CC-BY-4.0 -->
<!-- Generated by `i2w gallery build` from templates/{domain}/*.yml. \
Do not edit by hand. -->

# Gallery: {domain}

Auto-compiled from `templates/{domain}/*.yml`. Each section shows the bilingual
prompt for one template. Regenerate with `i2w gallery build`.

To use these prompts:
- **Path A (no Python):** copy a prompt block into web ChatGPT.
- **Path B (CLI):** `i2w template render <id> --vars <your-vars>.yml --out prompt.md`.

---
"""


def _vars_path_for(template_path: Path, templates_root: Path) -> Path | None:
    """Look up the demo-vars file for ``template_path`` from ``_DEMO_VARS_MAP``."""
    rel = f"{template_path.parent.name}/{template_path.stem}"
    mapped = _DEMO_VARS_MAP.get(rel)
    if mapped is None:
        return None
    candidate = templates_root / mapped
    return candidate if candidate.exists() else None


def _render_template_section(
    template_path: Path,
    templates_root: Path,
) -> str:
    """Return the markdown section for one template (no leading separator)."""
    spec = load_template(template_path)
    vars_path = _vars_path_for(template_path, templates_root)
    if vars_path is None:
        raise FileNotFoundError(
            f"no demo-vars mapping for {template_path}; "
            f"add an entry to gallery._DEMO_VARS_MAP"
        )
    vars_ = load_vars(vars_path)
    rendered = render_both(spec, vars_)

    art = spec.artifact
    descr = spec.description or art.type
    rel_vars = vars_path.relative_to(templates_root)
    parts: list[str] = []
    parts.append(f"## {spec.id}")
    parts.append("")
    parts.append(f"> {descr}")
    parts.append("")
    parts.append(
        f"**Artifact:** `{art.type}`, `{art.size}`, aspect `{art.aspect}`"
    )
    parts.append(f"**Demo vars:** `templates/{rel_vars}`")
    parts.append("")
    if "en" in rendered:
        parts.append("### English")
        parts.append("")
        parts.append("```")
        parts.append(rendered["en"])
        parts.append("```")
        parts.append("")
    if "zh-CN" in rendered:
        parts.append("### 中文")
        parts.append("")
        parts.append("```")
        parts.append(rendered["zh-CN"])
        parts.append("```")
        parts.append("")
    parts.append("---")
    parts.append("")
    return "\n".join(parts)


def _build_domain_file(
    domain: str,
    template_paths: list[Path],
    templates_root: Path,
) -> str:
    body = [_HEADER_TEMPLATE.format(domain=domain)]
    for tp in sorted(template_paths, key=lambda p: p.stem):
        body.append("")
        body.append(_render_template_section(tp, templates_root))
    return "\n".join(body).rstrip() + "\n"


@gallery_app.command("build")
def build(
    out_dir: Annotated[
        Path, typer.Option("--out-dir", help="Output directory for the gallery")
    ] = Path("docs/gallery"),
    domain: Annotated[
        str | None,
        typer.Option("--domain", help="Restrict to a single domain (e.g. business)"),
    ] = None,
) -> None:
    """Render every V1 template into its domain's gallery markdown file.

    Writes one file per domain under ``out_dir`` (e.g. ``business.md``).
    Skips ``index.md`` — that file is hand-curated. Returns the count of
    templates rendered and domain files written.
    """
    console = Console()
    out_dir.mkdir(parents=True, exist_ok=True)

    entries = catalog_index.list_templates(domain=domain)
    if not entries:
        console.print(
            f"no templates found (domain={domain!r})", markup=False
        )
        return

    templates_root = catalog_index._resolve_templates_dir()  # noqa: SLF001 — internal helper

    by_domain: dict[str, list[Path]] = {}
    for entry in entries:
        by_domain.setdefault(entry.domain, []).append(Path(entry.path))

    total_templates = 0
    domain_files = 0
    for dom, paths in sorted(by_domain.items()):
        content = _build_domain_file(dom, paths, templates_root)
        target = out_dir / f"{dom}.md"
        target.write_text(content, encoding="utf-8")
        domain_files += 1
        total_templates += len(paths)

    console.print(
        f"wrote {total_templates} templates across {domain_files} domain files",
        markup=False,
    )


__all__ = ["gallery_app"]
